version: '3'
services:
  web:
      build: .
      command: ./start.sh
      volumes:
        - .:/code
      ports:
        - "8080:8080"
      depends_on:
        - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydb

    ports:
      - "3306:3306"
