# Generated by Django 4.2.4 on 2023-08-03 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceCourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dancecourse',
            name='course_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_server.dancecoursetype'),
        ),
    ]
