# Generated by Django 4.2.4 on 2023-08-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_server', '0003_rename_dancecourse_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
